name = "dev"
description = ""
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["dev"]

[build-profiles]
"*" = "validation"

[[test]]
runner = "alire"
directory = "../aaa_base/tests"

[[test]]
runner = "alire"
directory = "../aaa_texts/tests"

[[depends-on]]
aaa_tests = "*"
aaa_texts_tests = "*"

[[pins]]
aaa_tests = { path = "../aaa_base/tests" }
aaa_texts_tests = { path = "../aaa_texts/tests" }
