name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        gnat_version: [^10, ^11]
        gprbuild_version: [^21]
    runs-on: ${{ matrix.os }}
    env:
      AAA_STYLE_CHECKS: enabled
      AAA_RUNTIME_CHECKS: enabled
      AAA_COMPILE_CHECKS: enabled
      AAA_CONTRACTS: enabled

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Alire and toolchain
      uses: alire-project/setup-alire@v1
      with:
        toolchain: gprbuild${{ matrix.gprbuild_version }} gnat_native${{ matrix.gnat_version }} --disable-assistant

    - name: Build
      run: alr -q build

    - name: Run tests
      run: cd tests && alr -q run
